apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*
        Refresh_Interval 5

    [OUTPUT]
        Name          cloudwatch
        Match         *
        region        us-east-2
        log_group_name /eks/logs
        auto_create_group true
        log_stream_name fluent-bit-stream

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
